### ISSUE TITLE
Literature data with missing values

### ISSUE THREAD

**Issue by nhadler** [alexarnimueller/surf#1]
Is there a suggested approach for dealing with literature data with missing values? For example a reaction may not have a reported stirring speed or specific analytical method specified. Should the value be left blank or a string like NA?

**Comment by alexarnimueller** [comment]
Hi Nicholas
Thanks for raising that point. So far, it works best if you just leave the fields blank.
Let me know if you need more info around SURF, happy to help.

**Comment by nhadler** [comment]
Thanks! Also, with the atmosphere column, is there any recommendations for how that should be formatted when it's composed of different gasses? Eg, varying ratios of CO and H2 in a hydroformylation. It seems like these should be included as reactants, and their partial pressures. This doesn't quite fill in right with only have the option for equivalents for reactants. Would doing "reactant_1_pressure" work?

**Comment by alexarnimueller** [comment]
This is a good point. So far there's no good way to encode mixtures of atmosphere gases. One could think of adding an atmosphere role and a pressure field, e.g. in atm.

**Comment by alexarnimueller** [comment]
actually I thought about it and what if you would encode the H2 and carbon monoxide as a reagent each? we could add a new global reaction column for pressure then

**Comment by alexarnimueller** [comment]
I think "reactant_1_pressure" would be the best solution 👍🏼
