### ISSUE TITLE
concat_surf.py missing

### ISSUE THREAD

**Issue by Takaogahara** [alexarnimueller/surf#3]
Thank you for creating this project and sharing it with the community!

I noticed that the script (`concat_surf.py`) mentioned in the section `Combining Multiple SURF Files` of the readme file is not available. I would like to know if you have the script and will commit it or if I should create my own.

Again, thank you for your contribution and efforts.

**Comment by alexarnimueller** [comment]
true, added just now 👍🏼 
thanks for spotting it

**Comment by alexarnimueller** [comment]
closing
